ext {

    Activity = 'androidx.activity:activity:1.13.0'
    FragmentKtx = 'androidx.fragment:fragment-ktx:1.8.9'

    Appcompat = 'androidx.appcompat:appcompat:1.7.1'
    Material = 'com.google.android.material:material:1.14.0'
    KtxCore = 'androidx.core:core-ktx:1.18.0'
    Constraintlayout = 'androidx.constraintlayout:constraintlayout:2.2.1'

    Recyclerview = 'androidx.recyclerview:recyclerview:1.4.0'
    LocalBroadcast = 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    Multidex = 'androidx.multidex:multidex:2.0.1'
    Annotation = 'androidx.annotation:annotation:1.9.1'
    Swiperefreshlayout = 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    AndroidViewModel = 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.10.0'
    AndroidLiveData = 'androidx.lifecycle:lifecycle-livedata-ktx:2.10.0'
    AndroidLifecycleRuntime = 'androidx.lifecycle:lifecycle-runtime-ktx:2.10.0'


    Gson = 'com.google.code.gson:gson:2.13.1'
    Okhttp = 'com.squareup.okhttp3:okhttp:4.12.0'
    Okio = 'com.squareup.okio:okio:3.15.0'

    Glide = 'com.github.bumptech.glide:glide:4.11.0'
    GlideProcessor = 'com.github.bumptech.glide:glide:4.11.0'

    AndroidEmoji2 = 'androidx.emoji2:emoji2:1.2.0'

    //google room 数据库
    Room = 'androidx.room:room-runtime:2.7.2'
    RoomAnnotationProcessor = 'androidx.room:room-compiler:2.7.2'

    blurview = 'com.github.Dimezis:blurview:version-3.2.0'
    prism4j = 'io.noties:prism4j:2.0.0'
    flexmark = 'com.vladsch.flexmark:flexmark-html2md-converter:0.64.8'
    ratexAndroid = 'io.github.erweixin:ratex-android:0.1.14'
}