plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt' //必须开启kapt
}

android {
    namespace = appNamespace
    compileSdk = appCompileSdk

    defaultConfig {
        applicationId = appApplicationId
        minSdk = appMinSdk
        targetSdk = appTargetSdk
        versionCode = appVersionCode
        versionName = appVersionName

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        flavorDimensions "default"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.schemaLocation":
                                     "$projectDir/../roomschemas".toString()]
            }
        }

    }

    signingConfigs {
        create("sign") {
            keyAlias = "key"
            keyPassword = "123456"
            storeFile = file("../test.jks")
            storePassword = "123456"
            enableV1Signing = true
            enableV2Signing = true
            enableV3Signing = true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.getByName("sign")
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.getByName("sign")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = "11"
    }

    buildFeatures {
        viewBinding = true
    }
}

configurations.all {
    exclude group: "org.jetbrains", module: "annotations-java5"
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation Activity
    implementation FragmentKtx
    implementation KtxCore
    implementation Appcompat
    implementation Material
    implementation Constraintlayout
    implementation Multidex

    implementation project(':chat:kit_chat')
    implementation project(':chat:kit_conversation')

    implementation project(':chat:kit_chat_ai')

    def markwon_version = "4.6.2"
    implementation "io.noties.markwon:core:$markwon_version"
    implementation "io.noties.markwon:syntax-highlight:$markwon_version" //代码高亮
    implementation "io.noties.markwon:linkify:$markwon_version" //链接
//    implementation "io.noties.markwon:ext-tables:$markwon_version"
    implementation "io.noties.markwon:recycler:$markwon_version"
    implementation "io.noties.markwon:recycler-table:$markwon_version"

    // prism4j 注解处理器，自动生成语法
    kapt("io.noties:prism4j-bundler:2.0.0") {
        exclude group: "org.jetbrains", module: "annotations-java5"
    }
}